image:
  - Visual Studio 2017
install:
  - set QTDIR=C:\Qt\5.12\mingw73_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%
build_script:
  - git fetch --prune --tags
  - qmake LimeReport.pro
  - mingw32-make
